---
title: "Student Dropout Dashboard"
editor: visual
format: dashboard
---

```{r}
library(tidyverse)
library(tidymodels)
library(janitor)
library(skimr)
library(GGally)
library(broom)
library(corrplot)
library(forcats)
library(scales)
library(purrr)
library(MASS)
library(rstatix)
library(randomForest)
library(caret)
library(pROC)

df <- read.csv("../data/dropout_data.csv", sep=";")
df <- clean_names(df)

df <- df %>%
  mutate(
    target = factor(target, levels = c("Dropout","Enrolled","Graduate")),
    dropout_bin = if_else(target == "Dropout", 0, 1),
    dropout_bin_f = factor(dropout_bin,
                           levels = c(0,1),
                           labels = c("Dropout","No dropout")))

set.seed(123)

train_index <- createDataPartition(df$dropout_bin_f, p = 0.7, list = FALSE)

train_data <- df[train_index, ]
test_data  <- df[-train_index, ]

rf_model <- randomForest(
  dropout_bin_f ~ . - dropout_bin - target,
  data = train_data,
  ntree = 500,
  importance = TRUE
)

rf_predictions <- predict(rf_model, test_data)

rf_confusion <- confusionMatrix(rf_predictions, test_data$dropout_bin_f)

logit_model <- glm(
  dropout_bin_f ~ . - dropout_bin - target,
  data = train_data,
  family = binomial
)

logit_predictions <- predict(logit_model, test_data, type = "response")

logit_class <- ifelse(logit_predictions > 0.5, "No dropout", "Dropout")

logit_class <- factor(logit_class, levels = c("Dropout","No dropout"))

logit_confusion <- confusionMatrix(logit_class, test_data$dropout_bin_f)
```

# Overview

## Dropout distribution

```{r}
ggplot(df, aes(x = dropout_bin_f, fill = dropout_bin_f)) +
  geom_bar() +
  scale_fill_manual(values = c("Dropout" = "#D55E00",
                               "No dropout" = "#0072B2")) +
  labs(
  title = "Student Dropout Distribution",
  x = "",
  y = "Number of students"
)

prop.table(table(df$dropout_bin_f))
```
# Model Performance

## Random Forest

::: {.row}

::: {.column}
### Accuracy
```{r}
rf_confusion$overall["Accuracy"]
```
:::

::: {.column}
### Sensitivity
```{r}
rf_confusion$byClass["Sensitivity"]
```
:::

::: {.column}
### Specificity
```{r}
rf_confusion$byClass["Specificity"]
```
:::

:::


## Logistic Regression

::: {.row}

::: {.column}
### Accuracy
```{r}
logit_confusion$overall["Accuracy"]
```
:::

::: {.column}
### Sensitivity
```{r}
logit_confusion$byClass["Sensitivity"]
```
:::

::: {.column}
### Specificity
```{r}
logit_confusion$byClass["Specificity"]
```
:::

:::